### ISSUE TITLE
Does not expand symbols?

### ISSUE THREAD

**Issue by ramiror** [federico-terzi/modulo#15]
I added `:em` to expand to `myemail@mycompany.com` but it expands to `myemail2mycompany.com`. Also `:expanso` expands to `Hi there1`

Ubuntu 18 with XMonad.

Also it does not work with xterm, only with gnome-terminal.
I did not install `modulo`

**Comment by federico-terzi** [comment]
Hey @ramiror,

I'm sorry you experienced this problem! Could you please try with this suggestion and see if that helps? https://github.com/federico-terzi/espanso/issues/579#issuecomment-773218483

Cheers :)

**Comment by federico-terzi** [comment]
Also, the new alpha v2 release should improve Terminal handling, so you might want to give that a try :) https://github.com/federico-terzi/espanso/issues/594#issuecomment-939329339

**Comment by ramiror** [comment]
> Hey @ramiror,
> 
> I'm sorry you experienced this problem! Could you please try with this suggestion and see if that helps? [federico-terzi/espanso#579 (comment)](https://github.com/federico-terzi/espanso/issues/579#issuecomment-773218483)
> 
> Cheers :)

Nice suggestion!! But it worsened. Now the replacement is empty (and in `gvim`, it gets me to the `verbatim` (`Ctrl-V`) mode).

Will try the alpha v2

**Comment by ramiror** [comment]
Alpha v2 solved my issue.
