### ISSUE TITLE
Modulo/Forms should accept dynamic list/choice values.

### ISSUE THREAD

**Issue by st0le** [federico-terzi/modulo#17]
Currently, Modulo only supports static lists in the config file.

What if we could have a new type or a subcategory of list/choice which gets lines from the output of a shell command or even source the list of values from the lines in a file?

**Comment by federico-terzi** [comment]
Hey @st0le,

Thank you for the feedback! This is already possible in the v2, here's what I suggest:
* Update to Espanso v2: https://github.com/federico-terzi/espanso/issues/594#issuecomment-939329339
* Then you can use the new variable injection mechanism, as shown here: https://espanso.org/docs/next/matches/examples/#populating-a-forms-choice-control-with-the-result-of-a-shell-command

This is an in-depth explanation: https://espanso.org/docs/next/matches/variables/#injecting-variables-inside-variables

Cheers :)

**Comment by st0le** [comment]
Amazing. Well done.

**Comment by st0le** [comment]
HI @federico-terzi , I just realized those are exclusive to espanso, are you planning to pull those changes into this repo? I think I might find use for modulo (without espanso) in my workflow.

**Comment by federico-terzi** [comment]
@st0le Given that Modulo is now part of Espanso, it's unlikely this repository will receive these updates. That said, you can still use Modulo _within Espanso_ by using the (currently undocumented) `espanso modulo` command.

So if you previously used:

```
modulo form -i "form.yml"
```

You should now write:

```
espanso modulo form -i "form.yml"
```

Hope that helps :)

**Comment by st0le** [comment]
Ack. Thanks.
