### ISSUE TITLE
Mac: On user press esc, it still return layout's text

### ISSUE THREAD

**Issue by yihou** [federico-terzi/modulo#9]
On user press <kbd>esc</kbd>, currently it still return the `layout` text.

I think it shouldn't output any text if user quit the form. The issue I met actually from espenso, form setup.

**Comment by federico-terzi** [comment]
Hey @yihou,

Thank you, I'm aware of the issue but I still have to determine which is the best way to handle it, as, at the moment, espanso expansions do not support stopping the expansion. Meaning that once you start the expansion, there is no way for the extensions to block the process. Hopefully, that will be possible one day, I've opened an issue https://github.com/federico-terzi/espanso/issues/475

I'm closing this one in favor of the other :)

**Comment by yihou** [comment]
well noted.
